version: "3.9"

services:

  db:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - ./postgre/data:/var/lib/postgresql/data
    environment:
      - PGDB_NAME=postgres
      - PGDB_USER=postgres
      - PGDB_PASSWORD=postgres
    expose:
      - 5432
    restart: always
  

  backend:
    build:
      context: .
      dockerfile: dockerfiles/dev/django/Dockerfile
    container_name: backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./core:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
    restart: always

    depends_on:
      # - redis
      - db


    # worker:
    #   build: .
    #   command: celery -A core worker --loglevel=info
    #   volumes:
    #     - ./core:/app
    #   depends_on:
    #     - redis
    #     - backend

    # redis:
    #   container_name: redis
    #   image: redis
    #   restart: always
    #   ports:
    #   - "6379:6379"
    #   command: redis-server --save 60 1 --loglevel warning

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

volumes:
  smtp4dev-data: